apiVersion: v1
kind: Service
metadata:
  name: echo-node-port
  labels:
    service-name: echo
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 80
      nodePort: 30030
      protocol: TCP
  selector:
    service-name: echo