apiVersion: v1
kind: Service
metadata:
  name: echo-service
  labels:
    service-name: echo
spec:
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
  selector:
    service-name: echo