apiVersion: apps/v1
kind: Deployment
metadata:
  name: probe-server-deployment
  labels:
    service-name: probe-server
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      service-name: probe-server
  template:
    metadata:
      labels:
        service-name: probe-server
    spec:
      containers:
        - name: probe-server
          image: lfyuomrgylo/probe-server
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /alive
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: probe-server-node-port
  labels:
    service-name: probe-server
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8080
      nodePort: 30031
      protocol: TCP
  selector:
    service-name: probe-server